dapr/docs

- concepts/README.md
> Fixed a typo

- README.md
Fixed typo for the word troubleshooting
> Fixed typo for the word troubleshooting

- README.md
Change-Id: I43dccd70387e2fd8e7c35605e75e9f526771308a
Signed-off-by: Philippe Coval <p.coval@samsung.com>
> docs: Fix link to API

- overview.md
Deduplicated building block description.
L30 and L34 describe the same `Distributed tracing between services`.
> Deduplicate building block description

- howto/create-grpc-app/Readme.md
Fix typo 'Dapr' instead of 'Dapper'.
> small typo fix

- concepts/actor/actors_features.md
> Fixed typos

- concepts/architecture/building_blocks.md
Link appears to be invalid pointing to README file.
> Fixed link

- best-practices/troubleshooting/profiling_debugging.md
- best-practices/troubleshooting/tracing.md
Fixes #29
Fix a few image links.
> Fix image links

- concepts/README.md
- concepts/distributed-tracing/README.md
Renamed logging-tracing to Distributed Tracing.  Fixed a few words along the way.
> Clean distributed tracing

- howto/autoscale-with-keda/README.md
> fix a typo in README.md

- concepts/actor/actors_features.md
Fixed product naming
Fixed typo's
I know you're trying to strive each PR to reference, and close an issue. But in this case it seems like overkill.
* ~Code compiles correctly~
* ~Created/updated tests~
* [*] Updated the documentation
> Fixed product naming in actors_features.md file

- concepts/distributed-tracing/README.md
- howto/diagnose-with-tracing/README.md
doc update for exporters becoming components
> doc update for exporters becoming components

- reference/api/actors.md
Adding response sample for GET http://localhost:<appPort>/v1.0/dapr/config
Closing #184
* [X ] Extended the documentation
> Adding response sample for /v1.0/dapr/config

- getting-started/environment-setup.md
Updated description on what dapr uninstall removes.  Added comment that uninstall must be run before later init's.
https://github.com/dapr/cli/issues/176 in CLI repo
> Update uninstall description

- concepts/actor/actor_overview.md
Adding more details about reminders, timers and configuration options into Actor Lifetime docs
#186
* [+] Extended the documentation
> Adding more details into Actor Lifetime

- README.md
> add document version

- README.md
Fix best-practices link.
Fixes #193
> Fix best-practices link

- reference/api/actors.md
- reference/api/bindings.md
- reference/api/pubsub.md
- reference/api/service_invocation.md
- reference/api/state.md
Removed 1.0 from Dapr to app calls and improved consistency
#194
* [x ] Extended the documentation
> improve API reference consistency 

- concepts/state-management/state-management.md
Fixed link to CosmosDB product in Azure.
Please reference the issue this PR will close: #199 
> Fixing a link to CosmosDB product page

- howto/setup-state-store/supported-state-stores.md
Originally the documentation is not reader friendly.
> Corrected the display of the documentation.

- getting-started/environment-setup.md
Document the uninstall --all option
This is related to https://github.com/dapr/cli/pull/184/ in the cli repo.
> Document the uninstall --all option

- concepts/README.md
- concepts/service-invocation/service-invocation.md
- howto/invoke-and-discover-services/README.md
Cross link service invocation docs and fix some related bugs
#209
> Improve service invocation docs

- howto/create-stateful-service/README.md
> Remove duplicate word "using"

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-azure-cosmosdb.md
- howto/setup-state-store/setup-cassandra.md
- howto/setup-state-store/setup-consul.md
- howto/setup-state-store/setup-etcd.md
- howto/setup-state-store/setup-memcached.md
- howto/setup-state-store/supported-state-stores.md
Adds How To tutorials for the following state stores:
* Cassandra
* etcd
* Consul
* Memcached
closes #215
> Add how to's for etcd, consul and cassandra

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-mongodb.md
- howto/setup-state-store/supported-state-stores.md
Adds a How To setup MongoDB guide and updates the supported state stores.
Closes #219
> Add MongoDB how to guide

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-zookeeper.md
- howto/setup-state-store/supported-state-stores.md
Add a Zookeeper How To guide and update the supported state stores.
> Add Zookeeper how to

- overview.md
Fix broken links to actor overview
> Fix broken links

- concepts/architecture/building_blocks.md
- concepts/distributed-tracing/README.md
Minor grammatical fix in the doc. [First push] ;)
> Documentation typo fix

- getting-started/cluster/setup-minikube.md
Updating doc to use latest Helm & Kubernetes for minikube
> Updating doc to use latest Helm & Kubernetes for minikube

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-firestore.md
- howto/setup-state-store/supported-state-stores.md
Add GCP Firestore to supported state stores + How To setup tutorial.
Closes #236
> Add GCP Firestore How To

- howto/setup-pub-sub-message-broker/README.md
- howto/setup-pub-sub-message-broker/setup-nats.md
Add NATS pub/sub How To tutorial.
Closes #220
> Add NATS How To

- howto/setup-state-store/setup-azure-cosmosdb.md
> Emphasize partition key role for CosmosDB

- howto/setup-pub-sub-message-broker/README.md
- howto/setup-pub-sub-message-broker/setup-azure-servicebus.md
> Add Azure Service Bus Topics How To

- concepts/actor/actors_features.md
Clarify state stores for actors, add list of supported ones, a to-be-added error message in dapr will point to this doc.
> Clarify state stores for actors, add list of supported ones

- reference/api/actors.md
Cleaned up wording, capitalization and such to make consistent.
> Clean up actors doc

- howto/diagnose-with-tracing/zipkin.md
Fix incorrect yaml name in doc.
> Fix yaml name

- howto/README.md
- howto/vscode-debugging-daprd/README.md
Updated docs with a section on configuring VSCode for debugging with daprd.
> Added section on Configuring VSCode for debugging with daprd

- walkthroughs/darprun.md
Describe the sequence of events when running `dapr run`.
Let me know if there's a better location for this doc.
Please reference the issue this PR will close: #_254_
> Describe the sequence of events when running dapr run

- getting-started/cluster/setup-aks.md
- getting-started/environment-setup.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Document the install process using Helm 3 (as the latest stable major release) and set as preferred
No specific issue ref
> (feat/docs): Add Helm 3 installation details

- concepts/README.md
> fix(docs): typo

- concepts/state-management/state-management.md
- howto/query-state-store/query-sqlserver-store.md
- howto/setup-state-store/setup-sqlserver.md
- howto/setup-state-store/supported-state-stores.md
Add SQL Server state store documentation
> Add SQL Server state store documentation

- concepts/state-management/state-management.md
- howto/query-state-store/query-cosmosdb-store.md
- howto/query-state-store/query-redis-store.md
- reference/api/state.md
Update delimit from __delim__ to || for human-readable
https://github.com/dapr/dapr/issues/914
> Update delimit to || in docs

- reference/api/actors.md
Updating Actor api refs to remove non transactional state apis.
> Updating Actor api refs to remove non transactional state apis.

- best-practices/troubleshooting/logs.md
- concepts/components/redis.md
- getting-started/cluster/setup-aks.md
- getting-started/cluster/setup-minikube.md
- getting-started/environment-setup.md
- howto/autoscale-with-keda/README.md
- howto/setup-pub-sub-message-broker/setup-nats.md
- howto/setup-pub-sub-message-broker/setup-rabbitmq.md
- howto/setup-pub-sub-message-broker/setup-redis.md
- howto/setup-state-store/setup-cassandra.md
- howto/setup-state-store/setup-consul.md
- howto/setup-state-store/setup-etcd.md
- howto/setup-state-store/setup-memcached.md
- howto/setup-state-store/setup-mongodb.md
- howto/setup-state-store/setup-zookeeper.md
Migrate from helm 2 to helm 3 to support the latest Dapr helm chart
https://github.com/dapr/dapr/issues/964
> Migrate from helm 2 to helm 3

- howto/send-events-with-output-bindings/README.md
Replaced the placeholder link to https://github.com/dapr/samples/tree/master/5.bindings
> Fixes #304

- howto/invoke-and-discover-services/README.md
> fix typo in invoke-and-discover-services

- concepts/state-management/state-management.md
> Fixed typo "full fill"

- howto/setup-secret-store/azure-keyvault-managed-identity.md
- howto/setup-secret-store/azure-keyvault.md
Adding documentation for kubernetes key vault secret store with managed identities as requested in [[WIP] Adding support for Manage Identities in the Azure Key Vault Secret Store](https://github.com/dapr/components-contrib/pull/185)
> Adding documentation for k8s key vault secret store with managed identities

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-azure-tablestorage.md
Extend documentation to add Azure Table Storage state store.
#320 
> Add Azure Table storage to the list of store providers

- concepts/bindings/README.md
- concepts/bindings/specs/twilio.md
> Add twilio binding docs

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-aerospike.md
- howto/setup-state-store/supported-state-stores.md
> add aerospike state store

- reference/api/state.md
Updating the state API spec documentation for new multi state stores APIs
Closes #294 
> Updating the state API spec documentation for new multi state stores APIs

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-hazelcast.md
- howto/setup-state-store/supported-state-stores.md
> Add Hazelcast docs

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-couchbase.md
- howto/setup-state-store/supported-state-stores.md
> Add couchbase how-to

- howto/setup-state-store/supported-state-stores.md
Update index with Azure Table Storage
> update azure table storae index

- howto/setup-secret-store/hashicorp-vault.md
- howto/setup-secret-store/supported-secret-stores.md
> Add hashicorp vault

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-cloudstate.md
- howto/setup-state-store/supported-state-stores.md
This adds how to setup Cloudstate alongside Dapr.
Partially closes #309 
/cc @jroper @viktorklang @jboner
> Add cloudstate how-to

- howto/setup-state-store/setup-cloudstate.md
/cc @jroper @viktorklang @jboner
> Add Cloudstate description

- howto/setup-state-store/setup-azure-cosmosdb.md
- howto/stateful-replicated-service/README.md
Updating state api usage for multi state store changes,
Fixes https://github.com/dapr/docs/issues/321
> Updating state api usage for multi state store changes,

- concepts/actor/actors_features.md
- reference/api/actors.md
Improves documentation for actor dueTime and period, including unusual cases.
Please reference the issue this PR will close: #325
> Better document dueTime and period

- howto/README.md
- howto/configure-mtls/README.md
> Add mTLS How To

- concepts/bindings/specs/eventhubs.md
Updated EventHubs binding spec to provide more clarity on connection string.
Partially addresses #298
> Added clarity to EventHub binding spec

- README.md
- howto/README.md
- howto/serialize/README.md
Document expected serialization in SDKs.
Link to example for Java actors.
Please reference the issue this PR will close: https://github.com/dapr/docs/issues/316
> Document expected serialization in SDKs.

- README.md
Add Docs and runtime version links
https://github.com/dapr/dapr/issues/1029
> Add 0.4.0 docs and runtime version links [DO-NOT-MERGE]

- best-practices/troubleshooting/common_issues.md
Part of https://github.com/dapr/dapr/issues/1087.
> Document DAPR_HOST_IP in troubleshooting section

- reference/api/actors.md
Add definitions of params inside /dapr/config -
actorIdleTimeout
actorScanInterval
drainOngoingCallTimeout
drainRebalancedActors
`drainRebalancedActors` may need updates later based on the decisions made on:
https://github.com/dapr/dapr/issues/1073
https://github.com/dapr/dapr/issues/1071
Please reference the issue this PR will close: https://github.com/dapr/docs/issues/363
> Add meanings of params in /dapr/config

- concepts/state-management/state-management.md
- howto/intellij-debugging-daprd/README.md
- howto/vscode-debugging-daprd/README.md
- walkthroughs/darprun.md
Replaced DaprID with AppID
Please reference the issue this PR will close: [#_[371]_](https://github.com/dapr/docs/issues/371)
> Replace DaprID with AppID

- reference/api/secrets.md
> Add secrets API reference

- concepts/bindings/README.md
- concepts/bindings/specs/storagequeues.md
> Add Azure Storage Queue binding info

- howto/diagnose-with-tracing/zipkin.md
> Update zipkin config for local mode

- concepts/middleware/middleware.md
Update link to register.go (loader.go no longer exists)
> Update middleware.md - Fix broken link

- concepts/middleware/middleware.md
- howto/README.md
Make "Authorization with oAuth" easily findable
> Link Authorization with oAuth

- howto/README.md
- howto/get-secrets/README.md
> Add Secrets API How To tutorial

- concepts/secrets/component-secrets.md
- howto/setup-secret-store/README.md
- howto/setup-secret-store/aws-secret-manager.md
- howto/setup-secret-store/gcp-secret-manager.md
> Add AWS/GCP Secret Stores

- concepts/README.md
- howto/README.md
- howto/components-scopes/README.md
> Add components authorization How To

- reference/specs/bindings/eventhubs.md
> Update Event Hubs binding spec

- concepts/actors/README.md
> Fix broken link

- reference/specs/bindings/eventhubs.md
> Link Event hub set up instructions

- monitoring/grafana/dashboards/system-services-dashboard.json
Adding grafana dashboard template for system services.
Closes #407 
> Adding grafana dashboard template for system services

- README.md
> Add 0.5.0 version note

- howto/setup-secret-store/hashicorp-vault.md
Fixes a small issue with the vault helm url where the `.` was getting included.
N/A: Small change
> fix: small issue with url

- reference/README.md
Fix broken link for templates
n/a
> Fix broken link for templates

- concepts/observability/README.md
Fix Prometheus + Grafana link to HowTo
> Fix Prometheus + Grafana link

- concepts/publish-subscribe-messaging/README.md
Fixed the link of pubsub API reference
> Fix broken doc of pubsub_api

- howto/setup-pub-sub-message-broker/README.md
- howto/setup-pub-sub-message-broker/setup-gcp.md
Add GCP Pubsub how to docs related to this https://github.com/dapr/components-contrib/issues/265
https://github.com/dapr/components-contrib/issues/265
> Add GCP pubsub docs

- README.md
- howto/diagnose-with-tracing/azure-monitor.md
- howto/diagnose-with-tracing/localforwarder/Dockerfile
- howto/diagnose-with-tracing/localforwarder/appinsight-tracing.yaml
- howto/diagnose-with-tracing/localforwarder/dapr-localforwarder.yaml
Add local forwarder docker and deployment yamls.
* Pushed localforwarder docker image to daprio org : https://hub.docker.com/r/daprio/dapr-localforwarder/tags
* Updated docs
https://github.com/dapr/components-contrib/issues/207
> Improve appinsight distributed trace setup guide and add deployment yamls

- reference/specs/bindings/eventhubs.md
Updated EventHub binding spec to include the information on sending the event to a single partition.
https://github.com/dapr/components-contrib/pull/269
> Update EventHub single partition id spec

- howto/setup-pub-sub-message-broker/README.md
- howto/setup-pub-sub-message-broker/setup-hazelcast.md
Add Hazelcast pubsub howto
https://github.com/dapr/docs/issues/453
> Add Hazelcast pubsub howto

- reference/api/error_codes.md
- reference/api/health_api.md
As the new Dapr /healthz API is added, this issue is to add the API spec document.
Feature Reference :
dapr/dapr#1288
Closes #455 
> Add the Dapr /healthz API spec

- reference/specs/bindings/blobstorage.md
- reference/specs/bindings/cosmosdb.md
- reference/specs/bindings/dynamodb.md
- reference/specs/bindings/eventhubs.md
- reference/specs/bindings/gcpbucket.md
- reference/specs/bindings/gcppubsub.md
- reference/specs/bindings/kafka.md
- reference/specs/bindings/mqtt.md
- reference/specs/bindings/rabbitmq.md
- reference/specs/bindings/redis.md
- reference/specs/bindings/s3.md
- reference/specs/bindings/servicebusqueues.md
- reference/specs/bindings/signalr.md
- reference/specs/bindings/sns.md
- reference/specs/bindings/sqs.md
- reference/specs/bindings/storagequeues.md
- reference/specs/bindings/twilio.md
Add metadata documentation to Azure Blob Storage Binding.
Please reference the issue this PR will close: dapr/components-contrib#280
> Add metadata doc to Azure Blob binding

- concepts/bindings/README.md
- reference/specs/bindings/kinesis.md
Add AWS Kinesis Bindings Docs
https://github.com/dapr/components-contrib/issues/272
> Add AWS kinesis docs

- reference/api/actors_api.md
> Update Actors health check endpoint

- reference/api/README.md
Adding the health API reference link in the Readme.
Closes #461
> Adding the health API reference link in the Readme.

- FAQ.md
* Escaped placeholders
* Small textual changes,  f.e. to underscore the instantiation of the actor. 
Closes #467
> Improve example creating actor

- howto/setup-pub-sub-message-broker/setup-hazelcast.md
- howto/setup-pub-sub-message-broker/setup-rabbitmq.md
Remove two formatting issues at PubSub HowTos
> Format pubsub HowTos

- concepts/security/README.md
Fixing the casing in the header texts.
> Fixing casing in doc headers

- howto/diagnose-with-tracing/azure-monitor.md
> Minor typo fix

- howto/pubsub-scopes/README.md
Some additional typos fixed.
Please reference the issue this PR will close: #448
> Fix typos in pubsub-scopes howto

- reference/dashboard/grafana/sidecar-dashboard.json
Add more information to charts and fix grpc  charts
Closes #497 
> Add more information to charts and fix grpc  charts

- getting-started/environment-setup.md
Add brew install instruction.
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/171
> Add brew install instruction.

- howto/setup-monitoring-tools/setup-prometheus-grafana.md
> Minor clarifications

- README.md
Updating the docs Readme to update 0.6.0 version
Part of release process.
> Updating the docs Readme to update 0.6.0 version

- reference/specs/bindings/kafka.md
Update Kafka binding with partition key metadata.
Closes #512
> Update Kafka binding

- concepts/observability/metrics.md
> Fix metrics docs link

- howto/diagnose-with-tracing/azure-monitor.md
fix missing subdirectory in --config option
n/a
> fix missing subdirectory in --config option

- concepts/bindings/README.md
- reference/specs/bindings/sendgrid.md
Fixes https://github.com/dapr/docs/issues/536
Adding docs for SendGrid
These are the docs updates for this new component in components-contrib
https://github.com/dapr/components-contrib/pull/308
> Adding docs for SendGrid

- howto/pubsub-namespaces/README.md
HowTo explaining using PubSub with multiple namespaces.
Please reference the issue this PR will close: #528 
> HowTo PubSub with multiple namespaces.

- reference/specs/bindings/twitter.md
This is the doc for Twitter search input binding for when that lands
#548
> Twitter search input binding

- howto/README.md
Add link to "Using PubSub across multiple namespaces" page into the HowTo list.
Please reference the issue this PR will close: #528
> Add pubsub-namespaces link

- concepts/observability/traces.md
Update the tracing configuration doc for standard tracecontext headers and new samplingRate configuration.
#550 
> Update the tracing configuration doc

- howto/diagnose-with-tracing/azure-monitor.md
- howto/diagnose-with-tracing/localforwarder/Dockerfile
- howto/diagnose-with-tracing/localforwarder/dapr-localforwarder.yaml
Update localforwarder version to latest
https://github.com/dapr/docs/issues/555
> Update localforwarder version to latest

- howto/setup-pub-sub-message-broker/README.md
- howto/setup-pub-sub-message-broker/setup-azure-eventhubs.md
> Add azure event hubs pub/sub how to

- README.md
Updating doc version table to have 0.7.0 entry
This is part of release process.
> Updating doc version table to have 0.7.0 entry

- concepts/bindings/README.md
> Update Event Grid in bindings index

- howto/autoscale-with-keda/README.md
The Keda Deploy hyperlink is broken.
No reference filed.
* [N/A] Code compiles correctly
* [N/A] Created/updated tests
* [N/A] Extended the documentation
> Fixing broken Keda Deployment doc hyperlink

- contributing/README.md
- contributing/howto-template.md
Adding more guidance details and template for `How To` article contribution.
> Adding guidance to How To article contribution

- howto/consume-topic/README.md
- reference/api/pubsub_api.md
> Update docs with pub/sub custom routes

- FAQ.md
- reference/api/actors_api.md
Update docs for change that removed activate message.
Please reference the issue this PR will close: #590
> Update docs to remove activate message.

- reference/api/service_invocation_api.md
#610 
Adds section to describe service invocation with nested paths in service URL
> Added section on support for multi-fragment paths 

- reference/api/state_api.md
Thank you for helping make the Dapr documentaion better!
> typo daprPort -> daprPor

- howto/setup-secret-store/README.md
- howto/setup-secret-store/json-secret-store.md
Adding JSON secret store how to
Please reference the issue this PR will close: #608
> Adding JSON secret store how to

- reference/specs/bindings/eventgrid.md
Added more information and practical example on how to get Azure Event Grid binding work in Kubernetes cluster.
> Added additional information and examples to Azure Event Grid binding's documentation

- howto/setup-pub-sub-message-broker/setup-azure-eventhubs.md
Updates Event Hubs Pub/Sub connection string details.
> Update Event Hubs doc

- FAQ.md
- howto/components-scopes/README.md
- howto/consume-topic/README.md
- howto/get-secrets/README.md
- howto/pubsub-scopes/README.md
- howto/send-events-with-output-bindings/README.md
- howto/setup-monitoring-tools/setup-prometheus-grafana.md
Added links to the useful videos that show demos of features from the community calls, so that people can see the feature in action as well as read about it
> Adding links to videos from the community calls.

- README.md
Add 0.8.0 Document version
https://github.com/dapr/dapr/issues/1619
> Add 0.8.0 Document version

- concepts/configuration/README.md
- getting-started/environment-setup.md
- howto/diagnose-with-tracing/zipkin.md
- howto/intellij-debugging-daprd/README.md
- walkthroughs/daprrun.md
Updating docs with respect to adding zipkin and enabling tracing on `dapr init`
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/342
> Updated docs for zipkin init

- howto/configure-mtls/README.md
Update default config to daprsystem config.
https://github.com/dapr/dapr/issues/1408
> Update default config to daprsystem config

- concepts/configuration/README.md
1. Fix for broken external links (lowercase readme.md)
2. Fix for internal section links
> Fixing broken links

- concepts/observability/W3C-traces.md
- howto/README.md
- howto/use-w3c-tracecontext/README.md
Improving the doc 
1.  Adding the trace context scenarios
2.  Explicitly mentioning about steps - how to create/pass/retrieve trace headers.
3. Performed more restructuring of the doc, so it is easy to navigate and understand the context.
4. Picked Go and C# language code snippets. For other languages, SDK link is given. 
Closes #654
> Adding Trace Context Scenarios and explicit steps to use trace context

- concepts/bindings/README.md
- reference/specs/bindings/cron.md
Documents the [cron binding](https://github.com/dapr/components-contrib/pull/386) PR'd in the `components-contrib` repo
> cron binding doc

- reference/specs/bindings/twitter.md
Updates the Twitter binding doc with the added support for output binding
https://github.com/dapr/components-contrib/pull/367
#651
> updated with output binding support

- getting-started/environment-setup.md
Added `sudo` requirement for linux.
_Please reference the issue this PR will close: https://github.com/dapr/cli/issues/380
> add readme note for uninstall in linux

- overview/README.md
A couple of typos in a table fixed, and consistently capitalization of Dapr.
N/A
> Fix a couple of typos.

- concepts/README.md
fix doc link and command usage in README.md
> fix doc link and command usage in README.md

- concepts/publish-subscribe-messaging/README.md
- howto/create-grpc-app/README.md
- howto/publish-topic/README.md
Updates cloud events mentions from 0.3 to 1.0.
> Update cloud events to 1.0

- concepts/observability/traces.md
fix a little typo of traces.md:
probabilistic and probability
N/A
> fix typo of traces

- howto/README.md
- howto/deploy-k8s-prod/README.md
This is the Kubernetes production-ready deployment and upgrade guidelines.
/cc @msfussell @youngbupark 
Feel free to add commits directly into this branch, however if possible please make note of the changes in comments.
The observability part is still TBD.
> Add k8s production deployment how-to

- reference/api/state_api.md
Updating the state API doc to remove the retry options behaviour.
Issue Reference : #724
> Removing the retry options behaviour in the doc

- howto/setup-secret-store/local-secret-store.md
Clarifying use of the nestedSeparator parameter in local secret store
_Please reference the issue this PR will close: #698_
> Clarifying use of the nestedSeparator parameter in local secret store #698

- getting-started/README.md
> Fix getting started broken link

- howto/authorization-with-oauth/README.md
Added the documentation explaining the usage of OAuth Client Credentials middleware from `components-contrib` PR https://github.com/dapr/components-contrib/pull/431
I also opened a PR for a quickstart example here https://github.com/dapr/quickstarts/pull/278
> Adding documentation for OAuth client credentials flow

- howto/publish-topic/README.md
- reference/api/pubsub_api.md
Fixes https://github.com/dapr/docs/issues/744
> updating docs for multi pubsub

- howto/intellij-debugging-daprd/README.md
- howto/self-hosted-no-docker/README.md
Fixes https://github.com/dapr/docs/issues/705
> Updating docs for change in dapr init behavior

- README.md
Updated docs and runtime versions as part of release
> Update docs and runtime versions as part of release

- getting-started/environment-setup.md
Update to env setup doc due to removal of flag in v0.10.0
> Removing --install-path ref in uninstall guidance

- howto/setup-secret-store/README.md
- howto/setup-secret-store/envvar-secret-store.md
- howto/setup-secret-store/file-secret-store.md
Docs to go along with the new env var and refactoring of file based secret stores
https://github.com/dapr/components-contrib/pull/444
> docs for env and changes to file secret store

- reference/api/actors_api.md
Api reference changes for issue https://github.com/dapr/dapr/issues/1973
> Remove non transactional delete, save actor state api

- reference/api/pubsub_api.md
> Adds pubsub name to subscription per v0.10 API

- reference/api/actors_api.md
Update corresponding to https://github.com/dapr/dapr/issues/1983.
> Update doc for actor get when key not found

- reference/api/actors_api.md
Update error code for actor not found.
> update actor api ref

- reference/api/state_api.md
Update StateAPI doc for GET/BULK GET State - metadata information
Closes #767
> Update StateAPI doc for GET/BULK GET State - metadata information

- howto/consume-topic/README.md
- reference/api/pubsub_api.md
> Update pub/sub subscriptions

- howto/consume-topic/README.md
Add more details on how to use in Kubernetes/Self-Hosted.
> Update declarative subscriptions

- howto/README.md
- howto/setup-monitoring-tools/observe-metrics-with-grafana.md
- howto/setup-monitoring-tools/setup-prometheus-grafana.md
Restructuring the steps for setting up Prometheus and Grafana dashboard.
Creating a separate doc to list instructions specific to observe metrics in grafana dashboard.
Closes #706
> Restructuring the steps for setting up Prometheus and Grafana dashboard

- concepts/bindings/README.md
updates check for output which was added in v0.10
> updates check for output which was added in v0.10

- howto/autoscale-with-keda/README.md
Updates how-to doc for KEDA v2.0 beta (currently the default version for KEDA)
> keda how to updates

- concepts/configuration/README.md
- howto/secrets-scopes/README.md
Add docs for allowlist for secrets
_Please reference the issue this PR will close: https://github.com/dapr/docs/issues/798
> Add docs for scoping secrets

- howto/README.md
- howto/policies-with-opa/README.md
Adds a reference how-to for using the opa middleware.
Closes #786
> docs: add opa middleware docs

- reference/api/state_api.md
Fix sample commands missing line continuations
> Fix sample commands missing line continuations

- howto/setup-monitoring-tools/setup-prometheus-grafana.md
Fixing broken link in the observability doc.
Closes # https://github.com/dapr/docs/issues/811
> Fixing broken link in the observability doc

- getting-started/environment-setup.md
migrate to new github helm chart repo
#815
> migrate to new github helm chart repo

- reference/specs/bindings/blobstorage.md
> Update azure blob storage binding

- howto/setup-monitoring-tools/setup-fluentd-es-kibana.md
Updates Dapr Helm repo location
> Updates Dapr Helm repo location

- concepts/observability/metrics.md
> Fix indentation in metrics config

- reference/api/pubsub_api.md
Add doc for pubsub response handling.
_Please reference the issue this PR will close: #772
> Add doc for pubsub response handling.

- howto/secrets-scopes/README.md
> changed defaultAcess to defaultAccess

- FAQ.md
Added FAQ on perf benchmark, since this question has been raised a few time in the community
> added FAQ on perf benchmark

- FAQ.md
Merging most recent master changes
> added FAQ on perf benchmark (#839)

- README.md
> Update README.md to add code of conduct

- concepts/bindings/README.md
- reference/specs/bindings/apns.md
I created the specification for the APNs output binding: dapr/components-contrib#481
> Create APNs Binding Specification

- howto/configure-k8s/README.md
- howto/invoke-and-discover-services/README.md
> Add ssl connection feature

- howto/setup-pub-sub-message-broker/setup-nats-streaming.md
consumerID and durableSubscriptionName is needed to get work without choosing only one.
> fix subscription options.

- daprdocs/content/en/contributing/contributing-docs.md
As this page suggests, headers should have sentence casing. Fixing 2 instances of that...
> Removing un-needed upper case

- daprdocs/config.toml
> Fix blog link in docs

- daprdocs/content/en/developing-applications/ides/vscode-remotecontainers.md
Fixed links in page https://docs.dapr.io/developing-applications/ides/vscode-remotecontainers/
_Please reference the issue this PR will close: #887
> fixed links in page VS Code remote containers

- daprdocs/content/en/operations/security/oauth.md
Fixed a small typo in the docs. I feel the right word here would be authorization.
> change authention to authorization

- daprdocs/content/en/operations/monitoring/azure-monitor.md
> fixed some typo

- daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md
add upgrade step from 0.11.x to 1.0.0
_Please reference the issue this PR will close: #908
> add upgrade step from 0.11.x to 1.0.0

- daprdocs/content/en/reference/api/actors_api.md
- daprdocs/content/en/reference/api/bindings_api.md
- daprdocs/content/en/reference/api/error_codes.md
- daprdocs/content/en/reference/api/health_api.md
- daprdocs/content/en/reference/api/pubsub_api.md
- daprdocs/content/en/reference/api/secrets_api.md
- daprdocs/content/en/reference/api/service_invocation_api.md
- daprdocs/content/en/reference/api/state_api.md
Update HTTP API reference docs to reflect what the code actually does. 
_Please reference the issue this PR will close: #899_
> Fix status code API reference documentation to match code (#899)

- daprdocs/content/en/operations/monitoring/grafana.md
- daprdocs/content/en/operations/monitoring/prometheus.md
> Fix prometheus and grafana Helm references

- daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md
- daprdocs/content/en/operations/hosting/self-hosted/self-hosted-no-docker.md
* Update self-host mode placement doc
* Update Kubernetes hosting mode for 1.0.0-rc.1
_Please reference the issue this PR will close: #898
> Update self-host / kubernetes hosting mode docs for 1.0.0-rc.1

- daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md
- daprdocs/content/en/operations/hosting/self-hosted/self-hosted-no-docker.md
- daprdocs/content/en/operations/monitoring/grafana.md
- daprdocs/content/en/operations/monitoring/prometheus.md
> Merge from master to v1.0.0-rc.1

- daprdocs/config.toml
- daprdocs/content/en/_index.md
- daprdocs/content/en/getting-started/configure-redis.md
- daprdocs/content/en/getting-started/install-dapr-cli.md
- daprdocs/content/en/getting-started/install-dapr-kubernetes.md
- daprdocs/content/en/getting-started/install-dapr.md
- daprdocs/content/en/getting-started/quickstarts.md
Update website (docs.dapr.io) with rc1 information
> Website version update

- daprdocs/config.toml
> Add labels to versions

- daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
Corrected the word **ensute** to **ensure**
> spelling error

- daprdocs/content/en/developing-applications/building-blocks/secrets/secrets-overview.md
Update links from old Github to new docs platform
> Update links to new docs platform

- daprdocs/content/en/getting-started/install-dapr-cli.md
Updating brew install instructions
> Update rc.1 brew command

- daprdocs/content/en/concepts/overview.md
I changed "is a simple as" to "is as simple as"
> Corrected typo on overview.md

- daprdocs/assets/scss/_sidebar-tree.scss
Addresses #891 
Removed min-width and used padding instead
> Removed min-width to fix resizing issue

- daprdocs/assets/scss/_sidebar-tree.scss
- daprdocs/config.toml
- daprdocs/layouts/partials/hooks/body-end.html
- Created new index on Algolia
- Reenabled algolia in config.toml
- Changed index name in header
> Reenable Algolia for RC1

- daprdocs/assets/scss/_sidebar-tree.scss
Fixed scss issue where content is pushed down
> Fixed SCSS

- daprdocs/content/en/operations/components/setup-secret-store/supported-secret-stores/azure-keyvault-managed-identity.md
Fixes: https://github.com/dapr/docs/issues/988
Fixed the configuration for AzureIdentity and AzureIdentityBinding cause fields are now case …
> Fix cause AAD Pod Identity fields are now case sensitive

- daprdocs/content/en/operations/configuration/configuration-overview.md
Document the new fields in Configuration's tracing section. This is a follow up of https://github.com/dapr/dapr/pull/2532 .
Fixes https://github.com/dapr/docs/issues/978
> Document the new fields in Configuration's tracing section.

- daprdocs/content/en/developing-applications/building-blocks/observability/tracing.md
- daprdocs/content/en/operations/monitoring/jaeger.md
- daprdocs/content/en/operations/monitoring/newrelic.md
- daprdocs/content/en/operations/monitoring/zipkin.md
- daprdocs/content/en/operations/troubleshooting/setup-tracing.md
- daprdocs/content/en/reference/api/metadata_api.md
Replace usage of exporter components with corresponding changes in Dapr Configuration.
_Please reference the issue this PR will close: https://github.com/dapr/docs/issues/967 and https://github.com/dapr/docs/issues/886_
> Update doc to remove usage of exporter component

- daprdocs/content/en/developing-applications/building-blocks/actors/actors-background.md
Updated some punctuation and a missing letter.
> Fixed a few typos.

- daprdocs/content/en/developing-applications/building-blocks/bindings/howto-triggers.md
> Updates binding concepts link

- daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> Clarifies declarative vs. programmatic pub/sub approach

- daprdocs/content/en/reference/cli/dapr-configurations.md
Update CLI ref for configurations with output and name params.
_Please reference the issue this PR will close: …
> Update CLI ref for configurations with output and name params.
