dapr/docs

- concepts/README.md
Whilst browsing the concepts documentation, I noticed a couple of 404s.  This PR fixes those broken links.
> Fixed broken links in concepts README

- concepts/components/redis.md
fixed issue where redis definition for state and pub sub was duplicated
https://github.com/dapr/docs/issues/157
> Fixed issue 157 (error in redis.yaml description)

- getting-started/environment-setup.md
Docker Desktop for Windows supports both Linux and Windows containers modes. When running Dapr via CLI as a standalone mode, dapr cli starts the container to run placement service. container image is built for linux container. therefore, Windows user needs to ensure that they are using Linux containers mode. This PR added the note to environment-setup document.
#162
> Add the note for Docker Desktop for windows

- reference/api/state.md
Fix some typos in [state.md](https://github.com/dapr/docs/blob/15a8e7c027/reference/api/state.md) file.
Please reference the issue this PR will close: #175 
> Typos for API reference's state management

- reference/api/state.md
Added backslash `\` to `shell` examples.
This closes #195
> fix missing backslashes in shell-examples

- getting-started/environment-setup.md
dapr init does not support non-default K8s namespaces 
dapr/dapr#657
* [x ] Extended the documentation
> dapr init only supports default namespace

- concepts/components/redis.md
Remove explicit Redis Helm version, not needed anymore
#216
> Remove explicit Redis Helm version

- howto/send-events-with-output-bindings/README.md
The JSON data in the curl example was not properly formatted so was generating an error when it was copied/pasted.
No issue to reference as I found it on my own.
* [_] Code compiles correctly
* [_] Created/updated tests
> Fixed CURL example JSON data.

- concepts/bindings/README.md
- reference/api/bindings.md
Add explanation how Dapr uses a OPTIONS request for determining which application wants to subscribe to a specific input binding.
Please reference the issue this PR will close: dapr/dapr#778
> add OPTIONS requests for input bindings

- howto/setup-pub-sub-message-broker/setup-redis.md
Corrected typo in documentation stating password should be placed in redisHost when it should be placed in redisPassword
> Updated error on password placement in setup-redis.md

- concepts/bindings/README.md
It took me a while to understand what `V` stands for in supported bindings table. I thought using checkmarks makes more sense
Feel free to ignore PR for any other reason
> Use checkmarks to show bindings support

- howto/setup-state-store/setup-redis.md
- Removed name flag 
- Removed Redis version (now that default version is >5 and therefore supports Redis Streams)
> updated to reflect helm 3 syntax

- howto/authorization-with-oauth/README.md
Added a type property to the `pipeline.handlers` in the sample dapr config as expected by the runtime.
Please reference the issue this PR will close: #296
> Fix incorrect dapr oauth2 middleware config

- howto/autoscale-with-keda/README.md
Fix broken install KEDA link, points now to https://keda.sh/deploy/
> Fix broken install KEDA link

- concepts/actor/actors_features.md
As SQL Server also supports the TransactionalStore interface it can also be used as an actor state store.
> Add SqlServer as another actor state store

- reference/api/pubsub.md
This PR removes an API endpoint that does not exist anymore in Dapr.
Closes https://github.com/dapr/docs/issues/375.
The actual API endpoints that are used in Dapr samples/how-to/code for pub/sub are correct.
> Remove broadcast in pub/sub

- reference/api/bindings.md
The binding docs api defined metadata payload is invalid json.
The docs suggest using an invalid json payload.
To work with the bindings WriteRequest we should use an object not an array:
```go
type WriteRequest struct {
Data     []byte            `json:"data"`
Metadata map[string]string `json:"metadata"`
}
```
Should be:
```json
{
"data": "",
"metadata": {
"": ""
}
}
```
> Update binding api docs - Invalid JSON

- concepts/publish-subscribe-messaging/README.md
Fixed a broken link in the pub/sub documentation
Didn't think this was worth opening an issue. Happy to do so if the maintainer's insist.
> Fix link to pub/sub API spec

- howto/configure-redis/README.md
This isn't included by default anymore in v3.
Added a link to the helm docs for adding the stable repo (which the instructions use)
This is a docs update, I can create an issue first if y'all really want :0
~~* [ ] Code compiles correctly~~ N/A
~~* [ ] Created/updated tests~~ N/A
> Link to instructions for adding helm stable repo

- FAQ.md
Autolinking is messing up the rendered page. This can't be easily fixed. Setting URL's as code seems the best solution.
For reference: https://gist.github.com/alexpeattie/4729247
> Fix autolinking mess

- howto/configure-mtls/README.md
Fixing typos in configure-mTLS readme.
> Fixing typo in configure-mTLS readme.

- howto/k8s-dapr-health/README.md
Adding document describing /healthz health endpoint in Dapr . Liveness/Readiness in Kubernetes and its configuration in Dapr sidecar container
Closes #475
> Adding doc on Kubernetes health Probe configuration with Dapr /healthz

- howto/autoscale-with-keda/README.md
Fixed doc:
- In order for the integration with _KEDA_ to work, the consumer group must be the same as the one defined in the component.
- Also the brokers field is no longer valid and the correct parameter is _bootstrapServers_
> consumerGroup must be the same in both manifests and fixed ScaledObject

- howto/setup-pub-sub-message-broker/setup-redis.md
- howto/setup-state-store/setup-redis.md
Updated Setup Redis doc to have instructions of how to enable or disable TLS for state.redis and pubsub.redis components
Please reference the issue this PR will close: [490](https://github.com/dapr/docs/issues/490)
> Include instructions to enable or disable TLS

- howto/setup-monitoring-tools/setup-fluentd-es-kibana.md
> Clarify some instructions

- howto/README.md
Fixed broken link to pubsub section [here](https://github.com/dapr/docs/tree/v0.6.0/howto#contents)
Please reference the issue this PR will close: N/A
> Fix broken link to pubsub section

- getting-started/environment-setup.md
- howto/README.md
- howto/configure-k8s/README.md
Today, users have no place they can look to see the supported sidecar configuration on Kubernetes.
The list of supported Dapr annotations are scattered in different places, and some of them are not even documented anywhere.
This PR adds a clear How To guide for configuring the Sidecar on Kubernetes with all the available annotations, their description and default values.
Closes #521
> Add kubernetes configuration how-to

- reference/specs/bindings/servicebusqueues.md
Adding quotes to the connectionString for Service Bus to work
Add quotes to the connectionString for Service Bus
> Add quotes to the connectionString

- reference/api/bindings_api.md
- reference/specs/bindings/rabbitmq.md
- reference/specs/bindings/servicebusqueues.md
- reference/specs/bindings/storagequeues.md
Add documentation about `ttlInSeconds` for bindings.
Needs to wait until https://github.com/dapr/components-contrib/pull/298 is merged.
Will close: #515 
> Add ttl documentation to RabbitMQ, Azure Service Bus/Storage Queue bindings

- reference/specs/bindings/storagequeues.md
ttlInSeconds parameter needs to be doublequoted or you get a very, very arcane error message complaining about an error from the ReadString method requires \" or n which took me quite a long time to figure out.
Please reference the issue this PR will close: #529 
https://github.com/dapr/docs/issues/529
[X] Extended the documentation
> Wrap value in doublequotes for ttlInSeconds value.

- howto/setup-pub-sub-message-broker/setup-azure-servicebus.md
- howto/setup-pub-sub-message-broker/setup-gcp.md
- howto/setup-pub-sub-message-broker/setup-hazelcast.md
- howto/setup-pub-sub-message-broker/setup-nats.md
- howto/setup-pub-sub-message-broker/setup-rabbitmq.md
Updated CLI docs to reflect the configuration file being renamed from `messagebus.yaml` to `pubsub.yaml`
Please reference the issue this PR will close: #505 
> PubSub config changed to pubsub.yaml

- reference/specs/bindings/redis.md
Now that we support TLS with redis binding component, updated the spec to show this option.
Please reference the issue this PR will close: #510 
> Update bindings.redis spec to have enableTLS option

- howto/setup-secret-store/azure-keyvault.md
- Adding `--encoding` flag to CLI to save steps for Windows/Linux
- Adding more detail on how to download from Azure Portal
> Simplifying certificate section of Azure Key Vault howto

- .github/pull_request_template.md
Helping contributors to docs repo make high quality contributions by adding links to the contribution guidance in the PR template.
> Added contribution guidance links in PR template

- howto/configure-redis/README.md
Add clarification around Azure Cache for Redis and remove the "disabling of TLS section" in favor of a way to add Redis Cache with TLS enabled. 
Also, fix some Markdown issues.
#580
> Update Azure Cache for Redis docs

- .github/pull_request_template.md
Corrects `documentation` spelling
> documentation spelling

- reference/specs/bindings/blobstorage.md
Setting file content in data.message creates an empty file.
Updated docs: file content should go into "data", and not "data.message".
> updated blobstorage docs

- howto/use-w3c-tracecontext/README.md
As the response headers changes are merged, updating the doc as how to retrieve the response headers.
> Updating the doc as how to retrieve the response headers

- concepts/observability/README.md
- concepts/observability/W3C-traces.md
- concepts/observability/traces.md
- howto/README.md
- howto/use-w3c-tracecontext/README.md
Separated into conceptual and HowTo docs. There was too much conceptual in the HowTo, which is about a Task to get done. 
Fix wording, grammar and typos.
Would like to see an example that is not Go, since this is a limited example and not that useful to most developers, so need to address this in another update to this doc. Personnally I did not follow the example and it was not made clear what the goal was. Let's add a scenario context in another update to this doc.
> Refactoring the Tracing docs into conceptual and HowTo 

- best-practices/troubleshooting/tracing.md
Addresses #572 
Current instructions for deploying Zipkin do not create service which makes the following command fail because there is no service, as starting with 1.15 k8s no longer creates service under the `run` command.
Changing the `run` to `create deployment`
```shell
kubectl create deployment zipkin --image openzipkin/zipkin
```
Which creates will allow the following command to create a service and expose its port.
```shell
kubectl expose deployment zipkin --type ClusterIP --port 9411
```
> deployment in stead of run for 1.15+ compatibility

- overview/README.md
Added docs describing behavior of `dapr-sidecar-injector` to inject 2 env vars into all the containers in the pod in which Dapr is enabled.
_Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1637
> Add docs for injecting env vars

- howto/setup-state-store/setup-azure-cosmosdb.md
This clarifies data sent to cosmos must be in json, just just json serializable.
> Cosmos - data must be in json

- reference/specs/bindings/cron.md
Remove programmability using output binding. That PR landed in master but has not been included in v0.9 dapr main so users have no access to it.
The dapr/dapr corresponding issue is [here](https://github.com/dapr/dapr/issues/1804)
> removes programmability, no cron output bind in .9

- howto/setup-state-store/README.md
- howto/setup-state-store/setup-azure-blobstorage.md
- howto/setup-state-store/supported-state-stores.md
Add the documentation on how to set up the Azure Blob Storage State Store. This documentation is for supporting Azure Blob Storage as State Store, using the key name as a filename and storing the value as blob contents.
This PR will close: #704
> Setup Azure Blob Storage Docs

- howto/autoscale-with-keda/README.md
Fix broken link to KEDA deployment in [Autoscaling a Dapr app with KEDA](https://github.com/dapr/docs/tree/master/howto/autoscale-with-keda)
Closes #710
> Fix broken link to KEDA deployment

- howto/send-events-with-output-bindings/README.md
- howto/trigger-app-with-input-binding/README.md
howto/send-events-with-output-bindings/README.md and howto/trigger-app-with-input-binding/README.md contain incorrect Component's metadata name.
metadata.name: Invalid value: "myEvent": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
N/A
> changed bindings metadata name with lowercase

- reference/api/service_invocation_api.md
The operator should be "+", because in the example the HTTP method is "/add"
> The operator should be "+"

- concepts/hosting/README.md
- concepts/observability/W3C-traces.md
- concepts/service-invocation/README.md
- getting-started/README.md
- howto/pubsub-namespaces/README.md
- howto/run-with-docker/README.md
- howto/self-hosted-no-docker/README.md
- howto/setup-secret-store/azure-keyvault.md
- howto/setup-secret-store/local-secret-store.md
- howto/trigger-app-with-input-binding/README.md
- howto/use-w3c-tracecontext/README.md
- overview/README.md
- presentations/README.md
- reference/api/pubsub_api.md
- walkthroughs/daprrun.md
This PR aims to fix broken links to samples after the renaming of the dapr/samples repo to dapr/quickstarts
Closes #736
> Fixing references to samples that are now quickstarts

- getting-started/README.md
Reverts dapr/docs#739
This broken link is fixed by https://github.com/dapr/quickstarts/pull/281
> Revert "Fix getting started broken link"

- getting-started/environment-setup.md
- howto/configure-mtls/README.md
- howto/deploy-k8s-prod/README.md
This PR updates the docs with the following:
1. Updates regarding new `dapr init -k` command and flags
2. Adds new `dapr mtls export` command to the deployment guide
> Update with new cli commands

- best-practices/troubleshooting/common_issues.md
Update docs to include guidance for when dapr sidecar initialization fails without logging anything (due to health check)
Fixes #729
> Update docs to include failed health check

- getting-started/environment-setup.md
This PR removes the mention of of --install-path flag from dapr init as the flag has been removed in v0.10.0
> Removing mention of dapr init flag --install-path

- reference/api/state_api.md
Remove `consistency` from HTTP bulk get API doc since it is not supported.
_Please reference the issue this PR will close: #783
> Remove `consistency`  from bulk API doc.

- concepts/observability/metrics.md
Updating doc to show how to disable metrics in Dapr runtime.
> Update metrics doc to list how to disable the Dapr runtime metrics

- howto/configure-redis/README.md
Add a disclaimer similar to that of https://github.com/dapr/quickstarts/tree/master/hello-kubernetes#step-2---create-and-configure-a-state-store so that users know that plaintext secrets aren't the norm, and how they can do things more securely.
> Add disclaimer about plaintext secrets

- concepts/configuration/README.md
- howto/secrets-scopes/README.md
Fixes the typo in the secrets README (`defaultAcess` -> `defaultAccess`)
Closes #833
> Replacing `defaultAcess` to `defaultAccess`

- getting-started/cluster/setup-aks.md
When originally written, the command to provision an aks cluster
had to specify a specific version of Kubernetes. The requirement
of having Kubernetes version 1.13.x or higher is now met by the
default version of Kubernetes in all regions.
Additionally, all clusters now have rbac enabled by default so this
option is also removed.
https://github.com/dapr/docs/issues/832
> Fix aks cluster provisioning command

- concepts/service-invocation/README.md
In the concepts directory, the service invocation [README.md](https://github.com/dapr/docs/tree/v0.11.0/concepts/service-invocation#pluggable-service-discovery) has a broken link to the hosting README. Fixed the broken reference 
No current issue exists for this fix
> Fixing broken link - hosting platform

- reference/api/bindings_api.md
Removed the "Sending Messages to Output Bindings" link
The "Sending Messages to Output Bindings" link was listed in the TOC but is not present
N/A
> Removed unused link in the bindings api docs

- presentations/README.md
The link to Mark Russinovich ignite session is dead. I've found the session on Youtube and replaced the link.
> Fix dead link to Ignite video session

- .github/pull_request_template.md
Updating PR template with info on docs website (see above why this is no longer correct...)
> Updating PR template with info on docs website

- daprdocs/content/en/reference/api/secrets_api.md
When deploying to namespace other than default the secret query must include namespace metadata
Example:
```shell
curl -i "http://localhost:3500/v1.0/secrets/kubernetes/test-secret?metadata.namespace=hardened"
```
> Update secret query example in namespace support

- daprdocs/content/en/concepts/middleware-concept.md
This is a minor fix to the broken link in the middleware pipelines page.
Currently shows up as
[How-To: Configure API authorization with OAuth(https://docs.dapr.io/operations/security/oauth/)
instead of
[How-To: Configure API authorization with OAuth](https://docs.dapr.io/operations/security/oauth/)
> Middleware pipelines: Fix link in next step section

- daprdocs/content/en/reference/api/pubsub_api.md
Synchronize website content to 0.11.0 tag
From https://github.com/dapr/docs/blob/v0.11.0/reference/api/pubsub_api.md#expected-http-response
_Please …
> fix website pubsub api docs to 0.11.0 tag content

- daprdocs/content/en/reference/api/error_codes.md
- daprdocs/content/en/reference/api/pubsub_api.md
- daprdocs/content/en/reference/api/service_invocation_api.md
Minor update to reflect that the APIs will return a 403 on ACL deny.
Please reference the issue this PR will close: #963
> Add 403 FORBIDDEN error to PubSub API documentation. (#963)

- daprdocs/config.toml
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>
Updated the reference to gitter in config.toml to use discord.
None
> Update footer to use discord instead of gitter

- daprdocs/config.toml
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>
Updated the reference to gitter in config.toml to use discord.
None
> Point to discord instead of gitter

- daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
- daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-overview.md
Document use of Content-Type as datacontenttype in pubsub.
_Please reference the issue this PR will close: #998
> Document use of Content-Type as datacontenttype in pubsub.

- daprdocs/content/en/developing-applications/building-blocks/state-management/query-state-store/query-redis-store.md
I changed "such querying states" to "such as querying states" by adding the word 'as'.
> Added missing word

- daprdocs/content/en/operations/components/setup-state-store/supported-state-stores/setup-sqlserver.md
Fixed typo. Changed 
"schema do use"
to
"schema to use"
> Fixed typo in setup-sqlserver

- daprdocs/content/en/reference/cli/dapr-publish.md
Update cli ref for publish command, adding publish-app-id.
_Please reference the issue this PR will close: https://github.com/dapr/cli/issues/536
> Update cli ref for publish command.
